# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 1
# language directory
# 语言目录
#contentDir = "content/en"
# language code
# 网站语言
# language code ["en", "zh-CN", "fr", "pl", ...]
# language name ["English", "简体中文", "Français", "Polski", ...]
languageCode = "en"
# language name
# 语言名称
languageName = "English"
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = false
# copyright description used only for seo schema
# 版权描述，仅用于 SEO
copyright = "This work is licensed under CC BY-NC-SA-4.0."


# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 1
  url = "/"
  [menu.main.params]
      icon = "fa-solid fa-home"
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Archives"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    parent = "archives"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
   [[menu.main]]
    identifier = "all"
    parent = "archives"
    pre = ""
    post = ""
    name = "All article"
    url = "/posts/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "tags"
    parent = "archives"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 5
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "collections"
    parent = "archives"
    pre = ""
    post = ""
    name = "Collections"
    url = "/collections/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-layer-group"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "It's me"
    url = "/about/"
    title = ""
    weight = 100
    [menu.main.params]
      icon = "fa-solid fa-heart"
   
